#!/bin/bash
#
# FAIRNode entrypoint
#
# Welcomes the operator, lets them choose a ROLE, generates a role-specific
# faircoin.conf, then execs faircoind. Mirrors the desktop app's role concept
# in a headless / Docker context.
#
# Roles (all run the same faircoind daemon, just configured differently):
#   node        (default) - relay/validate to support the network
#   staker      - node + wallet + staking enabled (produces PoS blocks)
#   masternode  - node + 5000 FAIR collateral + masternode service config
#
# Role is selected via the FAIRNODE_ROLE env var. If unset and a TTY is
# attached, the operator is prompted; otherwise it defaults to "node".

set -euo pipefail

CONF_DIR="/home/faircoin/.faircoin"
CONF_FILE="${CONF_DIR}/faircoin.conf"

# Network parameters (FairCoin v3.0.0 mainnet).
P2P_PORT="46372"

# Tip-age guard. Without a large max tip age a freshly started FairCoin v3 node
# can remain stuck in initial-block-download on an old tip. Keep this generous.
MAX_TIP_AGE="315360000"

log() {
    # Never log secrets here.
    echo "[entrypoint] $*"
}

# ---------------------------------------------------------------------------
# Role selection
# ---------------------------------------------------------------------------

# Normalise to lowercase; default empty so we can detect "unset".
ROLE="$(printf '%s' "${FAIRNODE_ROLE:-}" | tr '[:upper:]' '[:lower:]')"

prompt_for_role() {
    # Only reachable when stdin is a TTY.
    echo
    echo "  Welcome to FAIRNode - a FairCoin v3.0.0 node in a container."
    echo
    echo "  Choose how this node should participate in the network:"
    echo
    echo "    1) node        Support the network (relay + validate). [default]"
    echo "    2) staker      Run a wallet with staking enabled to earn"
    echo "                   Proof-of-Stake rewards."
    echo "    3) masternode  Provide masternode services backed by 5000 FAIR"
    echo "                   collateral and earn masternode rewards."
    echo
    local choice
    read -r -p "  Enter 1, 2 or 3 [1]: " choice || choice=""
    case "${choice}" in
        2 | staker) ROLE="staker" ;;
        3 | masternode) ROLE="masternode" ;;
        "" | 1 | node) ROLE="node" ;;
        *)
            echo "  Unrecognised choice '${choice}', defaulting to 'node'."
            ROLE="node"
            ;;
    esac
    echo
}

resolve_role() {
    if [ -n "${ROLE}" ]; then
        # Explicitly set via env var: validate it.
        case "${ROLE}" in
            node | staker | masternode) ;;
            *)
                log "ERROR: FAIRNODE_ROLE='${ROLE}' is invalid. Use one of: node, staker, masternode."
                exit 1
                ;;
        esac
        log "Role: ${ROLE} (from FAIRNODE_ROLE)"
        return
    fi

    # No role set. Prompt if interactive, otherwise default to node.
    if [ -t 0 ]; then
        prompt_for_role
        log "Role: ${ROLE} (selected interactively)"
    else
        ROLE="node"
        log "No FAIRNODE_ROLE set and no TTY attached; defaulting to role: node"
    fi
}

# ---------------------------------------------------------------------------
# Config generation
# ---------------------------------------------------------------------------

rand_token() {
    # 32 chars of URL-safe-ish randomness, no shell-special characters.
    head -c 48 /dev/urandom | base64 | tr -d '=+/' | head -c 32
}

require_env() {
    # require_env VAR_NAME "human description"
    local name="$1"
    local desc="$2"
    local value="${!name:-}"
    if [ -z "${value}" ]; then
        log "ERROR: ${name} is required for role 'masternode' (${desc})."
        log "       Set it via -e ${name}=... (docker run) or the environment block in docker-compose."
        exit 1
    fi
}

write_base_conf() {
    # $1 = rpcuser, $2 = rpcpassword
    local rpc_user="$1"
    local rpc_pass="$2"
    cat > "${CONF_FILE}" <<EOF
# Generated by FAIRNode entrypoint. Role: ${ROLE}
# Do not commit this file - it contains RPC credentials.

# --- RPC (localhost only) ---
rpcuser=${rpc_user}
rpcpassword=${rpc_pass}
rpcbind=127.0.0.1
rpcallowip=127.0.0.1

# --- Daemon / networking ---
server=1
listen=1
port=${P2P_PORT}
maxconnections=64
printtoconsole=1
daemon=0

# Prevent the node from getting stuck in initial-block-download on an old tip.
maxtipage=${MAX_TIP_AGE}
EOF
}

append_staker_conf() {
    cat >> "${CONF_FILE}" <<EOF

# --- Role: staker ---
# Wallet stays enabled (no disablewallet) so it can stake.
staking=1
EOF
}

append_masternode_conf() {
    # Secrets are written to the (chmod 600) config file, never logged.
    local mn_privkey="$1"
    local external_ip="$2"
    cat >> "${CONF_FILE}" <<EOF

# --- Role: masternode ---
masternode=1
masternodeprivkey=${mn_privkey}
externalip=${external_ip}
masternodeaddr=${external_ip}:${P2P_PORT}
EOF
}

generate_conf() {
    local rpc_user rpc_pass
    rpc_user="faircoin_$(rand_token | head -c 12)"
    rpc_pass="$(rand_token)"

    # Create with restrictive perms from the start (umask covers the heredoc).
    local old_umask
    old_umask="$(umask)"
    umask 077

    write_base_conf "${rpc_user}" "${rpc_pass}"

    case "${ROLE}" in
        node)
            : # base config is sufficient
            ;;
        staker)
            append_staker_conf
            ;;
        masternode)
            require_env MN_PRIVKEY "masternode private key from 'masternode genkey'"
            require_env EXTERNAL_IP "the public IP other nodes use to reach this masternode"
            # MN_PRIVKEY / EXTERNAL_IP are operator-supplied env vars (validated above).
            # shellcheck disable=SC2153
            append_masternode_conf "${MN_PRIVKEY}" "${EXTERNAL_IP}"
            ;;
    esac

    umask "${old_umask}"

    chmod 600 "${CONF_FILE}"
    log "Generated ${CONF_FILE} for role '${ROLE}' with random RPC credentials."
    log "RPC credentials are stored in faircoin.conf (perms 600); use faircoin-cli inside the container."
    if [ "${ROLE}" = "staker" ]; then
        log "Staker: fund the wallet, and if it is encrypted unlock it for staking:"
        log "  faircoin-cli walletpassphrase <passphrase> 0 true"
    fi
    if [ "${ROLE}" = "masternode" ]; then
        log "Masternode: complete setup from the controlling wallet (see README)."
        log "  Verify with: faircoin-cli masternode status"
    fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

mkdir -p "${CONF_DIR}"

resolve_role

if [ -f "${CONF_FILE}" ]; then
    # Respect an operator-supplied or previously generated config; never clobber
    # it (and never leak secrets by overwriting). Roles are applied at first run.
    log "Existing ${CONF_FILE} found; leaving it untouched."
    log "Delete it (or the data volume) to regenerate for a different role."
else
    generate_conf
fi

# Ensure the daemon user owns its data directory so faircoind can write the
# blockchain, wallet and logs. A read-only bind-mounted faircoin.conf can make
# the recursive chown fail on that single file; that's fine (the daemon only
# reads it), so warn instead of aborting the container.
if ! chown -R faircoin:faircoin "${CONF_DIR}" 2>/dev/null; then
    log "WARNING: could not chown every file under ${CONF_DIR} (read-only mount?); continuing."
    chown faircoin:faircoin "${CONF_DIR}" 2>/dev/null || true
fi

# Pin both datadir and conf explicitly so the daemon (and faircoin-cli run via
# `docker exec`) behave identically regardless of how HOME resolves under gosu.
exec gosu faircoin "$@" -datadir="${CONF_DIR}" -conf="${CONF_FILE}"
